import {Inter, Sora, Roboto_Condensed } from "next/font/google";
import "./globals.css";
import SmoothScroll from "./components/smoothScroll";
import Navbar from "./components/Navbar/navbar";
import Footer from "./components/Footer/footer";

const sora = Sora({
  variable: "--font-primary",
  subsets: ["latin"],
});

const inter = Inter({
  variable: "--font-secondary",
  subsets: ["latin"],
});


const robotoCondensed = Roboto_Condensed({
  variable: "--font-roboto",
  subsets: ['latin'],
  weight: ['700', '800', '900'],
})

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={`${inter.variable} ${sora.variable} ${robotoCondensed.variable}`}>
      <body>
        <SmoothScroll>
          <Navbar/>
          {children}
          <Footer/>
        </SmoothScroll>
      </body>
    </html>
  );
}
